package hexlet.code.games;

import hexlet.code.abstracts.GameBase;

import java.util.Scanner;

public final class Progression extends GameBase {
    private final int progressionLength = 10; //max numbers count in progression
    /**
     * Parameterized parental cctor.
     *
     * @param scanner Standard console input ref object
     */
    public Progression(Scanner scanner) {
        super(scanner);
    }

    @Override
    public void start(String name) {
        setName(name);


        System.out.println("What number is missing in the progression?");

        while (getSuccessCount() < getMaxSuccesses() && getSuccessCount() >= 0) {
            int progressionIncrement = getRandom().nextInt(getMinRandom(), getMaxRandom() + 1);
            int progressionStartValue = getRandom().nextInt(getMinRandom(), getMaxRandom() + 1);
            int missingValuePosition = getRandom().nextInt(0, progressionLength);
            int solution = progressionStartValue + missingValuePosition * progressionIncrement;

            System.out.print("Question: ");
            showProgression(progressionStartValue, progressionIncrement, missingValuePosition);
            System.out.print("Your answer: ");
            String userSuggestion = getScanner().nextLine();

            this.setSuccessCount(handleSuggestion(userSuggestion, solution, this.getSuccessCount()));
        }
        if (this.getSuccessCount() == getMaxSuccesses()) {
            System.out.println("Congratulations, " + name + "!");
        }
    }

    @Override
    public int handleSuggestion(String suggestion, int number, int count) {
        if (suggestion.equals(String.valueOf(number))) {
            System.out.println("Correct!");
            return ++count;
        }
        System.out.println("'" + suggestion + "' " + "is wrong answer ;(. "
                + "Correct answer was " + number);
        System.out.println("Let's try again, " + getName() + "!");
        count = -1;
        return count;
    }

    /**
     * Local method shows arithmetic progression randomly generated by parameters.
     * @param start First progression number
     * @param increment Progression step
     * @param position Position of element that must be replaced by dots in output
     */
    private void showProgression(int start, int increment, int position) {
        StringBuilder output = new StringBuilder();

        for (int i = 0; i < progressionLength; i++) {
            var currentSymbolToOutput = i == position ? ".." : start;
            output.append(currentSymbolToOutput).append(" ");
            start += increment;
        }
        System.out.println(output);
    }
}
