package hexlet.code.games;

import hexlet.code.Engine;
import hexlet.code.Utils;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public final class Progression {
    private static final int PROGRESSION_LENGTH = 10; //max numbers count in progression
    /**
     * Local method shows arithmetic progression randomly generated by parameters.
     * @param start First progression number
     * @param increment Progression step
     * @param progressionLength Progression length
     * @return Arithmetic progression represents string format
     */
    private static String[] getQuestionStatement(int start, int increment, int progressionLength) {
        String[] result = new String[progressionLength];
        for (int i = 0; i < progressionLength; i++) {
            result[i] = String.valueOf(start);
            start += increment;
        }
        return result;
    }
    public static void start() {
        String rules = "What number is missing in the progression?";
        Map<String, String> gameData = new HashMap<>(Engine.MAX_SUCCESSES_COUNT);

        for (int i = 0; i < Engine.MAX_SUCCESSES_COUNT; i++) {
            int progressionIncrement = Utils.getRandomInt(Engine.MIN_RANDOM_INT, Engine.MAX_RANDOM_INT);
            int progressionStartValue = Utils.getRandomInt(Engine.MIN_RANDOM_INT, Engine.MAX_RANDOM_INT);
            int missingValuePosition = Utils.getRandomInt(0, PROGRESSION_LENGTH);
            String[] progressArr = getQuestionStatement(progressionStartValue, progressionIncrement, PROGRESSION_LENGTH);
            progressArr[missingValuePosition] = "..";
            String question = String.join(" ", progressArr);
            int solution = progressionStartValue + missingValuePosition * progressionIncrement;
            String answer = String.valueOf(solution);
            gameData.put(question, answer);
        }
        Engine.execute(rules, gameData);
    }
}
